services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cyberimpact\CyberimpactSync\:
    resource: '../Classes/*'

  Cyberimpact\CyberimpactSync\Command\CheckConnectionCommand:
    tags:
      - name: 'console.command'
        command: 'cyberimpact:verifier-connexion'

  Cyberimpact\CyberimpactSync\Command\ScanImportFolderCommand:
    tags:
      - name: 'console.command'
        command: 'cyberimpact:scanner-dossier'

  Cyberimpact\CyberimpactSync\Command\ProcessNextRunCommand:
    tags:
      - name: 'console.command'
        command: 'cyberimpact:traiter-chunk'

  Cyberimpact\CyberimpactSync\Command\FinalizeRunCommand:
    tags:
      - name: 'console.command'
        command: 'cyberimpact:finaliser-run'

  Cyberimpact\CyberimpactSync\Command\RunFullImportCommand:
    tags:
      - name: 'console.command'
        command: 'cyberimpact:import-complet'
